name: task-flow

services:
  database:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - rb-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: rb-data

volumes:
  rb-data: